### ISSUE TITLE
tracking 0.3 breaking changes

### ISSUE THREAD

**Issue by jxs** [seanmonstar/warp#641]
- [x] https://github.com/seanmonstar/warp/pull/534 
- [x] https://github.com/seanmonstar/warp/pull/396
- [x] #645 
- [x] https://github.com/seanmonstar/warp/pull/753

**Comment by allenap** [comment]
#645 has a [comment](https://github.com/seanmonstar/warp/issues/645#issuecomment-735855360) saying it was done in #663. Does that unblock this issue?

**Comment by jxs** [comment]
#663 hasn't yet been merged

**Comment by dimlev** [comment]
#663 has been merged.

**Comment by seanmonstar** [comment]
Looks like all the breaking changes here are done (any new ones can be figured out for 0.4 or something).
