### ISSUE TITLE
Upgrade to Tokio v1

### ISSUE THREAD

**Issue by Urhengulas** [seanmonstar/warp#725]
**Dependencies which need to upgrade**
- [x] hyper (hyperium/hyper#2369)
- [x] tokio-rustls (tokio-rs/tls#46)
- [x] tokio-tungstenite (snapview/tokio-tungstenite#142)

**Comment by seanmonstar** [comment]
Yep, needs to happen in hyper first: https://github.com/hyperium/hyper/issues/2302

**Comment by Urhengulas** [comment]
> Yep, needs to happen in hyper first: [hyperium/hyper#2302](https://github.com/hyperium/hyper/issues/2302)

Yes, also saw that :)
The patch besides the hyper changes is quite small anyways.

<details>
<summary>bump-warp.patch</summary>

```diff
diff --git a/Cargo.toml b/Cargo.toml
index b40c2b5..89f681e 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -31,7 +31,7 @@ scoped-tls = "1.0"
 serde = "1.0"
 serde_json = "1.0"
 serde_urlencoded = "0.7"
-tokio = { version = "0.2", features = ["fs", "stream", "sync", "time"] }
+tokio = { version = "0.3", features = ["fs", "stream", "sync", "time"] }
 tracing = { version = "0.1", default-features = false, features = ["log", "std"] }
 tracing-futures = { version = "0.2", default-features = false, features = ["std-future"] }
 tower-service = "0.3"
@@ -47,7 +47,7 @@ tracing-subscriber = "0.2.7"
 tracing-log = "0.1"
 serde_derive = "1.0"
 handlebars = "3.0.0"
-tokio = { version = "0.2", features = ["macros"] }
+tokio = { version = "0.3", features = ["full"] }
 listenfd = "0.3"
 
 [features]
diff --git a/src/filters/fs.rs b/src/filters/fs.rs
index 1f04f6b..d4b9fc8 100644
--- a/src/filters/fs.rs
+++ b/src/filters/fs.rs
@@ -22,7 +22,6 @@ use hyper::Body;
 use mime_guess;
 use percent_encoding::percent_decode_str;
 use tokio::fs::File as TkFile;
-use tokio::io::AsyncRead;
 
 use crate::filter::{Filter, FilterClone, One};
 use crate::reject::{self, Rejection};
diff --git a/src/filters/sse.rs b/src/filters/sse.rs
index 8c4eda5..9d58492 100644
--- a/src/filters/sse.rs
+++ b/src/filters/sse.rs
@@ -54,7 +54,7 @@ use hyper::Body;
 use pin_project::pin_project;
 use serde::Serialize;
 use serde_json;
-use tokio::time::{self, Delay};
+use tokio::time::{self, Sleep};
 
 use self::sealed::{
     BoxedServerSentEvent, EitherServerSentEvent, SseError, SseField, SseFormat, SseWrapper,
@@ -467,7 +467,7 @@ impl KeepAlive {
         S::Ok: ServerSentEvent + Send,
         S::Error: StdError + Send + Sync + 'static,
     {
-        let alive_timer = time::delay_for(self.max_interval);
+        let alive_timer = time::sleep(self.max_interval);
         SseKeepAlive {
             event_stream,
             comment_text: self.comment_text,
@@ -484,7 +484,7 @@ struct SseKeepAlive<S> {
     event_stream: S,
     comment_text: Cow<'static, str>,
     max_interval: Duration,
-    alive_timer: Delay,
+    alive_timer: Sleep,
 }
 
 #[doc(hidden)]
@@ -505,7 +505,7 @@ where
     let max_interval = keep_interval
         .into()
         .unwrap_or_else(|| Duration::from_secs(15));
-    let alive_timer = time::delay_for(max_interval);
+    let alive_timer = time::sleep(max_interval);
     SseKeepAlive {
         event_stream,
         comment_text: Cow::Borrowed(""),
```
</details>

**Comment by jxs** [comment]
there's also the dependency on [`tokio-tungstenite`](https://github.com/snapview/tokio-tungstenite) and [`tokio-rustls`](https://github.com/tokio-rs/tls/tree/master/tokio-rustls).
`tokio-rustls` already has a PR upgrading it: https://github.com/tokio-rs/tls/pull/29

**Comment by pomazanbohdan** [comment]
https://github.com/seanmonstar/reqwest/issues/1060

**Comment by vn971** [comment]
Note that currently, warp can start with `tokio` being explicitly set to 0.3, and it will then fail *at run-time*. I wonder if we can/should tackle this problem so that it doesn't affect us in the future? E.g. so that the same run-time error cannot cannot appear in future tokio releases (if applicable).

I'm really happy to see that the problem is being addressed in all the referenced projects though, thanks a lot for keeping it up-to-date!

**Comment by Urhengulas** [comment]
> Note that currently, warp can start with `tokio` being explicitly set to 0.3, and it will then fail _at run-time_. I wonder if we can/should tackle this problem so that it doesn't affect us in the future? E.g. so that the same run-time error cannot appear in future tokio releases (if applicable).
> 
> I'm really happy to see that the problem is being addressed in all the referenced projects though, thanks a lot for keeping it up-to-date!

@vn971 That is a very good idea. I had this problem in my project, that I thought I successfully upgraded to `tokio 0.3`, but then it actually failed on runtime, since dependencies are using `tokio 0.2`.

What would be an approach to avoid that for the future? Let `tokio` check the dependency tree on compile-time?

**Comment by MikailBag** [comment]
For example, warp can explicitly take `tokio::runtime::Handle` for server construction. That way it's always visible in user code which tokio version is used by warp.

**Comment by aknuds1** [comment]
Is this being worked on in a branch?

**Comment by Urhengulas** [comment]
> Is this being worked on in a branch?

I started in #725, but feel free to take over :)

**Comment by aknuds1** [comment]
@Urhengulas ok thanks, I will try.

**Comment by aknuds1** [comment]
@Urhengulas I made my own PR, where I managed to get all tests to pass (`cargo test --all-features`): https://github.com/seanmonstar/warp/pull/753.

**Comment by phungleson** [comment]
Hey everyone, wonder if `tokio 0.3.0` will be merged soon?

**Comment by novacrazy** [comment]
Likewise, just ran into issues with this that were mind-boggling until I realized the versions were different, and indeed a Tokio 0.2 reactor was not running, only 0.3

**Comment by xue35** [comment]
I just noticed that examples/hello.rs does not run with tokio 0.3. Switching back to tokio 0.2 runs perfectly.

**Comment by hosunrise** [comment]
Are we ready to upgrade to `tokio 0.3`?

**Comment by slyshykO** [comment]
@hosunrise Think update to _tokio 1.0_ more likely :) 
If also have in mind https://github.com/hyperium/hyper/pull/2369

**Comment by hosunrise** [comment]
@sinkuu Wow `tokio 1.0` is released 🚀🚀🚀🚀!!
So, are we ready to upgrade to `tokio 1.0`?

**Comment by songday** [comment]
> 
> 
> @sinkuu Wow `tokio 1.0` is released 🚀🚀🚀🚀!!
> So, are we ready to upgrade to `tokio 1.0`?

Not yet, but I guess soon  
Since `hyper` just released 0.14.1 which supports `tokio 1.0`

**Comment by simonsan** [comment]
Would it make sense to widen the scope of this issue and jump to `tokio-v1.0` directly?

**Comment by aknuds1** [comment]
@simonsan My [PR](https://github.com/seanmonstar/warp/pull/753) upgrades to tokio 1.0.

**Comment by simonsan** [comment]
> @simonsan My [PR](https://github.com/seanmonstar/warp/pull/753) upgrades to tokio 1.0.

Is there an issue to relate to for tracking?

**Comment by aknuds1** [comment]
@simonsan This issue.

**Comment by songday** [comment]
> 
> 
> > @sinkuu Wow `tokio 1.0` is released 🚀🚀🚀🚀!!
> > So, are we ready to upgrade to `tokio 1.0`?
> 
> Not yet, but I guess soon
> Since `hyper` just released 0.14.1 which supports `tokio 1.0` and `tokio-rustls` also upgraded
> Only `tokio-tungstenite` left

Currently, the last component `tokio-tungstenite` depends `tungstenite-rs` which depends `http`  
`http` v0.2.3 https://github.com/hyperium/http/pull/463 will be released soon (I guess)

**Comment by mraerino** [comment]
[`tokio-tungstenite v0.13.0`](https://github.com/snapview/tokio-tungstenite/releases/tag/v0.13.0) has been released with the fix: https://github.com/snapview/tokio-tungstenite/pull/142

**Comment by bkontur** [comment]
Hello, is there any date for release warp with new tokio?

**Comment by extrawurst** [comment]
It was merged! 
Now we only need a release :)
